name: Terraform Deploy Component

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      component:
        required: true
        type: string
    secrets:
      TFVARS_CONTENT:
        required: true

jobs:
  deploy:
    runs-on: [ self-hosted ]
    environment: ${{ inputs.env }}

    env:
      TF_WORKING_DIR: ./stacks/${{ inputs.env }}/${{ inputs.component }}
      TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

      OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
      OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
      OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
      TF_HTTP_USERNAME: ${{ secrets.TF_HTTP_USERNAME }}
      TF_HTTP_PASSWORD: ${{ secrets.TF_HTTP_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Create tfvars
        run: printf "%s" "$TFVARS_CONTENT" > terraform.auto.tfvars
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TFVARS_CONTENT: ${{ secrets.TFVARS_CONTENT }}

      - name: Terraform Init
        run: terraform init -input=false -no-color -lock-timeout=60s
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -input=false -no-color -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
