name: Destroy Fuzzer

on:
  workflow_dispatch:

jobs:
  destroy-compute:
    uses: ./.github/workflows/destroy-component.yml@dev
    with:
      env: fuzzer
      component: compute
    secrets: inherit

  destroy-network:
    needs: destroy-compute
    uses: ./.github/workflows/destroy-component.yml@dev
    with:
      env: fuzzer
      component: network
    secrets: inherit
